apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-consul-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-consul-template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-consul-template
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-tls-secret: vault-tls
        vault.security.banzaicloud.io/vault-ct-configmap: hello-consul-template
        vault.security.banzaicloud.io/vault-agent: "false"
        # vault.security.banzaicloud.io/vault-skip-verify: "false"
        # vault.security.banzaicloud.io/vault-role: "default"
        # vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "while true; do cat /vault/secrets/aws_credentials; sleep 2; done"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-consul-template
  labels:
    app.kubernetes.io/name: hello-consul-template
data:
  config.hcl: |
    vault {
      ssl {
        ca_cert = "/vault/tls/ca.crt"
      }
      retry {
        backoff = "1s"
      }
    }
    template {
      contents = <<EOH
        {{- with secret "secret/data/accounts/aws" -}}
        [default]
        aws_access_key_id = {{ .Data.data.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key = {{ .Data.data.AWS_SECRET_ACCESS_KEY }}
        {{- end -}}
      EOH
      destination = "/vault/secrets/aws_credentials"
    }
